# Generated by Django 6.1 on 2026-09-21 17:38

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
import questions_module.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_module', '0005_alter_access_options_remove_fieldofstudy_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='متن گزینه')),
                ('image', models.ImageField(blank=True, upload_to='questions/choice_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), questions_module.models.validate_question_image_size], verbose_name='تصویر گزینه')),
                ('is_correct', models.BooleanField(default=False, verbose_name='گزینه درست')),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': 'گزینه\u200cها',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام درس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='questions_module.category', verbose_name='دسته مادر')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام فصل')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_chapters', to='users_module.subject', verbose_name='درس ثبت\u200cشده')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='questions_module.course', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل\u200cها',
                'ordering': ['subject__title', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'چهارگزینه\u200cای'), ('DES', 'تشریحی')], default='MCQ', max_length=3, verbose_name='نوع سوال')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='متن سوال')),
                ('image', models.ImageField(blank=True, upload_to='questions/question_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), questions_module.models.validate_question_image_size], verbose_name='تصویر سوال')),
                ('difficulty', models.CharField(choices=[('E', 'آسان'), ('M', 'متوسط'), ('H', 'دشوار')], default='M', max_length=2, verbose_name='سطح دشواری')),
                ('explanation', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='پاسخ تشریحی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='approved', max_length=20, verbose_name='وضعیت تأیید')),
                ('approval_note', models.TextField(blank=True, verbose_name='یادداشت تأیید/رد')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_questions', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions_module.category', verbose_name='دسته')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questions_module.chapter', verbose_name='فصل')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='طراح سوال')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'چهارگزینه\u200cای'), ('DES', 'تشریحی')], default='MCQ', max_length=3, verbose_name='نوع سؤال')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='تعداد کل سوالات')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='تعداد درست')),
                ('wrong_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نادرست')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نزده')),
                ('percent', models.FloatField(default=0.0, verbose_name='درصد')),
                ('requested_difficulty', models.CharField(blank=True, choices=[('E', 'آسان'), ('M', 'متوسط'), ('H', 'دشوار')], max_length=2, verbose_name='سطح انتخابی')),
                ('difficulty_breakdown', models.JSONField(blank=True, default=dict, verbose_name='ترکیب سطح سؤال\u200cها')),
                ('status', models.CharField(choices=[('in_progress', 'در حال انجام'), ('done', 'پایان یافته')], default='in_progress', max_length=20, verbose_name='وضعیت')),
                ('chapters', models.ManyToManyField(related_name='practice_sessions', to='questions_module.chapter', verbose_name='فصل\u200cها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('questions', models.ManyToManyField(related_name='practice_sessions', to='questions_module.question', verbose_name='سوالات')),
            ],
            options={
                'verbose_name': 'جلسه تمرین',
                'verbose_name_plural': 'جلسات تمرین',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='پاسخ تشریحی کاربر')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='پاسخ درست')),
                ('revealed', models.BooleanField(default=False, verbose_name='مشاهده جواب')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='زمان پاسخ')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='questions_module.choice', verbose_name='گزینه انتخابی')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions_module.practicesession', verbose_name='جلسه تمرین')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questions_module.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ تمرین',
                'verbose_name_plural': 'پاسخ\u200cهای تمرین',
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'چهارگزینه\u200cای'), ('DES', 'تشریحی')], default='MCQ', max_length=3, verbose_name='نوع سؤال')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='مهلت زمانی')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='تعداد کل سوالات')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='تعداد درست')),
                ('wrong_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نادرست')),
                ('unanswered_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نزده')),
                ('percent', models.FloatField(default=0.0, verbose_name='درصد')),
                ('requested_difficulty', models.CharField(blank=True, choices=[('E', 'آسان'), ('M', 'متوسط'), ('H', 'دشوار')], max_length=2, verbose_name='سطح انتخابی')),
                ('difficulty_breakdown', models.JSONField(blank=True, default=dict, verbose_name='ترکیب سطح سؤال\u200cها')),
                ('status', models.CharField(choices=[('in_progress', 'در حال انجام'), ('done', 'پایان یافته')], default='in_progress', max_length=20, verbose_name='وضعیت')),
                ('auto_submitted', models.BooleanField(default=False, verbose_name='ثبت خودکار (اتمام زمان)')),
                ('chapters', models.ManyToManyField(related_name='exam_sessions', to='questions_module.chapter', verbose_name='فصل\u200cها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('questions', models.ManyToManyField(related_name='exam_sessions', to='questions_module.question', verbose_name='سوالات')),
            ],
            options={
                'verbose_name': 'جلسه آزمون',
                'verbose_name_plural': 'جلسات آزمون',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='پاسخ تشریحی کاربر')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='پاسخ درست')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='زمان پاسخ')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='questions_module.choice', verbose_name='گزینه انتخابی')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions_module.examsession', verbose_name='جلسه آزمون')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questions_module.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ آزمون',
                'verbose_name_plural': 'پاسخ\u200cهای آزمون',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questions_module.question', verbose_name='سوال'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام مبحث')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='questions_module.chapter', verbose_name='فصل')),
            ],
            options={
                'verbose_name': 'مبحث',
                'verbose_name_plural': 'مباحث',
                'ordering': ['chapter__subject__title', 'chapter__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questions_module.topic', verbose_name='مبحث'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='practice_sessions', to='questions_module.topic', verbose_name='مباحث'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='exam_sessions', to='questions_module.topic', verbose_name='مباحث'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('subject', 'name'), name='unique_chapter_per_subject'),
        ),
        migrations.AlterUniqueTogether(
            name='practiceanswer',
            unique_together={('session', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='examanswer',
            unique_together={('session', 'question')},
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('chapter', 'name'), name='unique_topic_per_chapter'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active', 'question_type'], name='questions_m_is_acti_632927_idx'),
        ),
    ]
